# Generated by Django 3.2.6 on 2021-08-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=255, verbose_name='Subreddit Name')),
                ('regex_pattern', models.CharField(max_length=100, verbose_name='Regex Pattern')),
                ('number_of_mentions', models.IntegerField(default=0)),
            ],
        ),
    ]
