# Generated by Django 3.2.6 on 2021-08-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='submission_title',
            field=models.CharField(choices=[('Q4G2Q3LS6E', 'JR'), ('69B8UTPFDJ', 'GR'), ('FQSZ9RAZ4Y', 'SO'), ('ZD5YJNTJV8', 'JR'), ('0R0WKX6B1E', 'SO'), ('9Z34GC9G7G', 'FR'), ('9FDYF3KXTD', 'SO'), ('L7C4UYJJHZ', 'GR'), ('NUNX5M0YFT', 'FR'), ('C7YUV0AP18', 'SR')], default='Anyting Title', max_length=500),
        ),
    ]
