# Generated by Django 3.2.6 on 2021-08-25 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wsb', '0002_subreddit_submission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 19, 53, 346054, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='submission_title',
            field=models.CharField(choices=[('Q47JZGUXKQ', 'JR'), ('Q9XRQBII6O', 'SO'), ('VG66F7QOJN', 'SO'), ('CMH362M6O4', 'FR'), ('A4ZTDXLNMJ', 'FR'), ('PMSP1PXX7V', 'GR'), ('AB3NAEDCZO', 'SO'), ('OK8VX90I55', 'JR'), ('IFUF3XDQPO', 'JR'), ('CJNVZ47S1Z', 'GR')], default='Anyting Title', max_length=500),
        ),
    ]
