# Generated by Django 3.2.6 on 2021-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsb', '0003_auto_20210825_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='post_date',
            field=models.DateTimeField(default=None, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='submission_title',
            field=models.CharField(choices=[('6VR9VAEZ9J', 'GR'), ('FFXQY42ZIR', 'FR'), ('123HHXR0RY', 'FR'), ('G6QRXT14K5', 'SR'), ('1PSSC5WO3P', 'SR'), ('5WE0TNBB4G', 'GR'), ('EBGMNN02UY', 'SO'), ('X8688BP0BY', 'JR'), ('J7YYJOW3U2', 'SR'), ('MXP772YW02', 'FR')], default='Anyting Title', max_length=500),
        ),
    ]
