# Generated by Django 3.2.6 on 2021-08-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsb', '0004_auto_20210825_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='submission_title',
            field=models.CharField(default='Anyting Title', max_length=500),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='author',
            field=models.ForeignKey(default='wsb_god', on_delete=django.db.models.deletion.CASCADE, to='wsb.author'),
            preserve_default=False,
        ),
    ]
