# Generated by Django 3.2.6 on 2021-08-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsb', '0006_auto_20210826_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
