# Generated by Django 3.2.6 on 2021-08-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsb', '0007_auto_20210826_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
