# Generated by Django 3.2.6 on 2021-08-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsb', '0008_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='author name')),
                ('comment_text', models.CharField(max_length=200, verbose_name='commentary text')),
            ],
        ),
    ]
